### ISSUE TITLE
Migration of users

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/migrate_express#44] opened 2024-06-17 18:13 UTC
Blocked users and users without roles are being migrated to the D10 sites.

Example: https://www.colorado.edu/volunteer/ - https://live-ucbprod-volunteer.pantheonsite.io

**Comment by jcsparks** [comment] 2024-06-18 16:00
duplicate of #33

**Comment by jcsparks** [comment] 2024-06-18 20:53
Fixed now

**Closed as completed by jcsparks** 2024-06-18 20:53 UTC
Labels: bug, duplicate
